### ISSUE TITLE
Noice

### ISSUE THREAD

**Issue by testman42** [Athou/commafeed-ui#1]
Wait, didn't you say that you stopped developing further functionality for Commafeed?

I am pleasantly surprised and very thankful that you keep supporting the project, as I am very commited, very devoted user of Commafeed.

**Comment by Athou** [comment]
I've been playing with Typescript and React for a couple of days, using CommaFeed as a guide for learning new things.

This is more of a playground as I wanted to be able to discuss the code with friends so I put it online.
I don't know if I'm going to re-implement everything yet but I like how things fall into place so far; coming from Java, Typescript is a joy to work with :)

**Comment by davd** [comment]
I am a fully trained rubber duck who is helping by just listening.

**Comment by ebraminio** [comment]
It is so nice to see this is active, the new UI is so awesome code and design wise, great work here! Thank you so much!

**Comment by Athou** [comment]
I archived this repository and moved the code to the develop branch of th main commafeed repo. 
See announcement here https://github.com/Athou/commafeed/discussions/1015!
